[package]
name = "technical-indicators"
version = "1.0.1"
edition = "2021"
description = "A library of technical indicators for financial analysis"
authors = ["Celsis Durham <durhamcelsis@gmail.com>"]
license = "MIT"
repository = "https://github.com/rustic-ml/technical-indicators"
documentation = "https://docs.rs/technical-indicators"
readme = "README.md"
keywords = ["finance", "technical-analysis", "trading", "indicators", "stocks"]
categories = ["finance", "mathematics", "stock-market", "ohlcv", "time-series", "technical-indicators"]

[dependencies]
polars = { version = "0.46.0", features = ["lazy", "strings", "temporal", "rolling_window"] }
chrono = "0.4.34"
thiserror = "2.0.11"
ndarray = "0.16.1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
approx = "0.5.1"
